services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: catuser
      POSTGRES_PASSWORD: catpass
      POSTGRES_DB: catdb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  cat-service:
    build: ./cat-service
    environment:
      PGUSER: catuser
      PGPASSWORD: catpass
      PGDATABASE: catdb
      PGHOST: postgres
      PGPORT: 5432
    ports:
      - 3000:3000
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alert.rules.yml:/etc/prometheus/alert.rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    depends_on:
      - cat-service
      - postgres_exporter

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3001:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://catuser:catpass@postgres:5432/catdb?sslmode=disable
    ports:
      - 9187:9187
    depends_on:
      - postgres

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--log.level=debug'

  locust:
    image: locustio/locust
    ports:
      - 8089:8089
    volumes:
      - ./cat-service/load_test:/mnt/locust
    working_dir: /mnt/locust
    command: -f locustfile.py --host http://cat-service:3000
    depends_on:
      - cat-service

  telegram-bot-init:
    image: node:18-alpine
    volumes:
      - ./telegram-bot-init.js:/app/telegram-bot-init.js
    working_dir: /app
    command: node telegram-bot-init.js
    depends_on:
      - alertmanager

volumes:
  pgdata:
  grafana_data: